// <auto-generated />
using BibliotecaADMComputadores.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdmComputadores.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230830180617_Migracao1")]
    partial class Migracao1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BibliotecaADMComputadores.Models.Computador", b =>
                {
                    b.Property<int>("ComputadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputadorId"), 1L, 1);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("HD")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MarcaHD")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MemoriaRAM")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PlacaMae")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VelocidadeProcessador")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("ComputadorId");

                    b.ToTable("Computadores");
                });
#pragma warning restore 612, 618
        }
    }
}
