name: Build Angular App

on:
  push:
    branches:
      - master, develop  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version required for your project

    - name: Install dependencies
      run: npm install
      working-directory: AdmComputadoresAppV2.0/AdmComputadoresAppV2.0/src  # Adjust the directory path

    - name: Build Angular app
      run: npm run build
      working-directory: AdmComputadoresAppV2.0/AdmComputadoresAppV2.0  # Adjust the directory path

    - name: Check if build succeeded
      run: |
        if [ -d "dist" ]; then
          echo "Build succeeded!"
        else
          echo "Build failed!"
          exit 1
        fi
      working-directory: AdmComputadoresAppV2.0/AdmComputadoresAppV2.0  # Adjust the directory path

  codeql-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Autobuild CodeQL database
      uses: github/codeql-action/autobuild@v1
      with:
        languages: javascript
        overwrite: true

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
