name: Build Angular App

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version required for your project

    - name: Install dependencies
      run: npm install
      working-directory: AdmComputadores/AdmComputadoresApp/AdmComputadoresApp  # Adjust the directory path

    - name: Build Angular app
      run: npm run build -- --prod
      working-directory: AdmComputadores/AdmComputadoresApp/AdmComputadoresApp  # Adjust the directory path

    - name: Check if build succeeded
      run: |
        if [ -d "dist" ]; then
          echo "Build succeeded!"
        else
          echo "Build failed!"
          exit 1
        fi
      working-directory: AdmComputadores/AdmComputadoresApp/AdmComputadoresApp  # Adjust the directory path
