on: [push, pull_request]

name: ChatGPT CodeReview

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - name: ChatGPT comment
        uses: kxxt/chatgpt-action@v0.3
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: ${{ secrets.CHATGPT_SESSION_TOKEN }}
          split: 'yolo'  # Use true to enable the unstable split feature.
        env:
          GITHUB_TOKEN: 'ZNzFSmngNe5kby0ouZ6RzH.BIUauXwWfJKF0LCV33BY-1674755957-0-1-cb0b2fc.af09c18e.f7f3874-160'
